server:
  port: 8082
  servlet:
    context-path: /community

spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3302/test?seUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        connectionTimeoutMilliseconds: 3000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 1
        maintenanceIntervalMilliseconds: 30000
      slave:
        url: jdbc:mysql://127.0.0.1:3303/test?seUnicode=true&characterEncoding=utf-8
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        connectionTimeoutMilliseconds: 3000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 1
        maintenanceIntervalMilliseconds: 30000
    rules:
      readwrite-splitting:
        data-sources:
          glapp:
            write-data-source-name: master
            read-data-source-names:
              - master
            load-balancer-name: roundRobin # 负载均衡算法名称
        load-balancers:
          roundRobin:
            type: ROUND_ROBIN # 一共两种一种是 RANDOM（随机），一种是 ROUND_ROBIN（轮询）

  mail:
    host: smtp.163.com
    port: 465
    username: aiden_chiang@163.com
    password: CVONMRQALTRTUNLN
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: aiden.nowcoder.community.entity

community:
  path:
    domain: http://localhost:8082